#!/usr/bin/env python3
"""Install a Python startup hook that makes WSL reuse the Windows HF cache."""

from __future__ import annotations

import argparse
import os
import site
import sys
from pathlib import Path


BOOTSTRAP_TEMPLATE = r'''# Auto-generated by Multimodal-RAG install_wsl_hf_cache_hook.py.
# Python imports sitecustomize at interpreter startup, before transformers or
# huggingface_hub read their cache environment variables.
from __future__ import annotations

import os
import platform


def _truthy(value: str | None, default: bool) -> bool:
    if value is None:
        return default
    return value.strip().lower() not in {"0", "false", "no", "off"}


def _running_in_wsl() -> bool:
    if os.environ.get("WSL_DISTRO_NAME"):
        return True
    try:
        return "microsoft" in platform.release().lower()
    except Exception:
        return False


def _configure_multirag_hf_cache() -> None:
    if not _running_in_wsl():
        return

    hf_home = os.environ.get("WSL_WINDOWS_HF_HOME") or "__HF_HOME__"
    if not os.path.isdir(hf_home):
        return

    force_cache = _truthy(os.environ.get("MULTIRAG_FORCE_WSL_HF_CACHE"), True)

    def set_cache_var(name: str, value: str) -> None:
        if force_cache or not os.environ.get(name):
            os.environ[name] = value

    set_cache_var("HF_HOME", hf_home)
    set_cache_var("HF_HUB_CACHE", os.path.join(hf_home, "hub"))
    set_cache_var("HF_DATASETS_CACHE", os.path.join(hf_home, "datasets"))

    # The notebooks are intended to use the pre-populated Windows cache in WSL.
    # Set MULTIRAG_HF_ALLOW_DOWNLOADS=true before launching Python if you need
    # this environment to download new Hugging Face files.
    offline = _truthy(os.environ.get("MULTIRAG_HF_OFFLINE"), True)
    allow_downloads = _truthy(os.environ.get("MULTIRAG_HF_ALLOW_DOWNLOADS"), False)
    if offline and not allow_downloads:
        os.environ.setdefault("HF_HUB_OFFLINE", "1")
        os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")


_configure_multirag_hf_cache()
'''


def site_packages_path() -> Path:
    site_packages = site.getsitepackages()
    if not site_packages:
        raise RuntimeError("Could not locate site-packages for this Python environment.")
    return Path(site_packages[0])


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--hf-home",
        default=os.environ.get(
            "WSL_WINDOWS_HF_HOME",
            "/mnt/c/Users/danie/.cache/huggingface",
        ),
        help=(
            "Windows Hugging Face cache path as seen from WSL. Defaults to "
            "WSL_WINDOWS_HF_HOME, then /mnt/c/Users/danie/.cache/huggingface."
        ),
    )
    args = parser.parse_args()

    site_dir = site_packages_path()
    site_dir.mkdir(parents=True, exist_ok=True)

    bootstrap = site_dir / "multirag_wsl_hf_cache_bootstrap.py"
    bootstrap_content = BOOTSTRAP_TEMPLATE.replace("__HF_HOME__", args.hf_home)
    bootstrap_changed = write_if_changed(bootstrap, bootstrap_content)

    # A .pth import runs while site.py processes the virtualenv site-packages,
    # before third-party packages read Hugging Face cache constants. This also
    # works when the system Python already has its own sitecustomize.py.
    pth = site_dir / "multirag_wsl_hf_cache.pth"
    pth_changed = write_if_changed(pth, "import multirag_wsl_hf_cache_bootstrap\n")

    # Keep a sitecustomize copy as a fallback for environments without a system
    # sitecustomize. The .pth file above is the primary hook.
    sitecustomize = site_dir / "sitecustomize.py"
    sitecustomize_changed = write_if_changed(sitecustomize, bootstrap_content)

    print(f"Installed WSL Hugging Face cache bootstrap: {bootstrap}")
    print(f"Installed virtualenv startup hook: {pth}")
    print(f"Installed fallback sitecustomize: {sitecustomize}")
    if not any([bootstrap_changed, pth_changed, sitecustomize_changed]):
        print("Hook files were already up to date.")
    print(f"Windows HF cache path: {args.hf_home}")
    print("Downloads are blocked by default in this WSL Python.")
    print("Set MULTIRAG_HF_ALLOW_DOWNLOADS=true before Python startup to allow downloads.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
